apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment # define what kind of work we are doing
metadata:
  name: second-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-app
      tier: backend
  template: # create pods and define the container inside it
    metadata:
      labels:
        app: second-app # define the label for the pod
        tier: backend
    spec:
      containers:
      - name: second-app-container
        image: samchangdev/kub-first-app:3
    